name: Release

on:
  push:
    branches:
      - main
      - beta
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - CONTRIBUTING.md
      - renovate.json
      - ".github/workflows/**"
      - .releaserc.yml
      - .scalafix.conf
      - .scalafmt.conf
      - "package*.json"
      - codecov.yml
  workflow_dispatch:

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-20.04
    env:
      TERM: dumb
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup scala environment
        uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.17
      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
      - name: Import GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install
      - name: Publish on GitHub
        id: publish
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
      - name: Generate scaladoc
        if: steps.publish.outputs.release == 1
        run: sbt doc
      - name: Publish scaladoc on GitHub Pages
        if: steps.publish.outputs.release == 1
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/scala-3.2.1/api