name: Review

on:
  pull_request:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  review:
    name: Analyze for review
    needs:
      - test
    runs-on: ubuntu-20.04
    env:
      TERM: dumb
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download coverage data from GitHub
        uses: actions/download-artifact@v3.0.2
        with:
          name: coverage
          path: target/scala-3.2.2-RC2/scoverage-report
      - name: SonarCloud scan fixed
        uses: pervasive-cats/sonarcloud-scoverage-fix@v1.0.0
        with:
          scoverageReport: target/scala-3.2.2-RC2/scoverage-report/scoverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
